[cursor]
style = "Beam"

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.7
blur = true
decorations = "Transparent"
[window.padding]
x = 6
y = 0

#[window.dimensions]
#columns = 90
#lines = 25

[colors]
  [colors.primary]
    background = "#1a1b26"
    foreground = "#a9b1d6"

  [colors.search.matches]
    foreground = "CellBackground"
    background = "#ee5396"

#[colors.search.footer_bar]
#   background = "#262626"
#foreground = "#ffffff"

  [colors.normal]
    black=   '#32344a'
    red=     '#f7768e'
    green=   '#9ece6a'
    yellow=  '#e0af68'
    blue=    '#7aa2f7'
    magenta= '#ad8ee6'
    cyan=   '#449dab'
    white=   '#787c99'

  [colors.bright]
    black=   '#444b6a'
    red=     '#ff7a93'
    green=   '#b9f27c'
    yellow=  '#ff9e64'
    blue=    '#7da6ff'
    magenta= '#bb9af7'
    cyan=    '#0db9d7'
    white=   '#acb0d0'
